
abstract=
ontologyTitle=INELOD VOC
ontologyPrefix=ine
ontologyNamespaceURI=http://lod.ine.es/def/vocabulary/
ontologyName=INELOD VOC
thisVersionURI=http://lod.ine.es/def/vocabulary/1.0.0
latestVersionURI=
previousVersionURI=
dateCreated=2025-05-01
dateModified=2025-09-23
ontologyRevisionNumber=1.0.0
licenseURI=https://creativecommons.org/licenses/by/4.0/legalcode
licenseName=https://creativecommons.org/licenses/by/4.0/legalcode
licenseIconURL=null
citeAs=Diego Conde-Herreros. INELOD VOC. Revision: 1.0.0. Retrieved from: http://lod.ine.es/def/vocabulary/1.0.0
DOI=
status=Ontology Specification Draft
logo=
description=An ontology for describing the variables used as dimensions and measures in the RDF data cubes from the Instituto Nacional de Estadística
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Diego Conde-Herreros
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=Diego Conde-Herreros
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
